create docs

diff --git a/src/viralscan/Snakefile b/src/viralscan/Snakefile
--- a/src/viralscan/Snakefile
+++ b/src/viralscan/Snakefile
@@ -25,11 +25,17 @@ rule kb_count:
 
         # Check for whitelist
         if [ "{config[whitelist]}" = "None" ] || [ -z "{config[whitelist]}" ]; then
-            kb count -i {config[index]} -g {config[transcripts]} --overwrite -o {config[output]} -x {config[technology]} {config[sample1]} {config[sample2]} --h5ad 2> /dev/null
+            output_log=$(kb count -i {config[index]} -g {config[transcripts]} --overwrite -o {config[output]} -x {config[technology]} {config[sample1]} {config[sample2]} --h5ad 2> /dev/null)
         else
-            kb count -i {config[index]} -g {config[transcripts]} --overwrite -o {config[output]} -x {config[technology]} -w {config[whitelist]} {config[sample1]} {config[sample2]} --h5ad 2> /dev/null
+            output_log=$(kb count -i {config[index]} -g {config[transcripts]} --overwrite -o {config[output]} -x {config[technology]} -w {config[whitelist]} {config[sample1]} {config[sample2]} --h5ad 2> /dev/null)
         fi
         
+        # Check for "no reads pseudoaligned" in the log
+        if echo "$output_log" | grep -q "no reads pseudoaligned"; then
+            echo -e "\033[0;31mERROR: kb count failed! No reads pseudoaligned. Check your sample or reference index.\033[0m"
+            exit 1
+        fi
+
         touch {output}
         echo -e "\033[0;32mQuantifying the data is done!\033[0m"
         mkdir {config[output]}kb-python/
